/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.SITE_URL || 'https://www.stardustcreatornetwork.com',
  generateRobotsTxt: true, // Generate robots.txt file
  sitemapSize: 7000, // Split sitemap if it exceeds this number of URLs
  changefreq: 'weekly',
  priority: 0.7,

  // Exclude certain paths from sitemap
  exclude: [
    '/admin/*',
    '/api/*',
    '/dashboard/*',
    '/404',
    '/500',
    '/_*',
    '/og/*', // Exclude OG image generation routes
    '/creator-community', // Exclude redirect page
    '/creators/join', // Exclude if it redirects
    '/join/*', // Exclude auth/signup flows
    '/pricing-calculator/success', // Exclude success/thank-you pages
    '/pricing-calculator/invoice', // Exclude invoice preview (part of calculator flow)
    '/pricing-calculator/invoice/edit', // Exclude invoice edit page
    '/*.png', // Exclude image files
    '/*.jpg',
    '/*.jpeg',
    '/*.webp',
    '/*.svg',
    '/*.gif',
    '/*.ico',
    '/sitemap-0.xml', // Don't include the sitemap itself
    '/sitemap.xml', // Don't include the sitemap index
    '/robots.txt', // Don't include robots.txt
  ],

  // Transform function to customize URLs in sitemap
  transform: async (config, path) => {
    // Custom priority based on path
    let priority = 0.7;
    let changefreq = 'weekly';

    if (path === '/') {
      priority = 1.0;
      changefreq = 'daily';
    } else if (path.startsWith('/blog/')) {
      priority = 0.8;
      changefreq = 'weekly';
    } else if (path.startsWith('/(marketing)/')) {
      priority = 0.6;
      changefreq = 'monthly';
    }

    return {
      loc: path,
      changefreq,
      priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
    };
  },

  // Additional paths to include (useful for dynamic routes)
  additionalPaths: async () => {
    const result = [];

    try {
      // Add blog posts dynamically from Sanity CMS
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const { createClient } = require('next-sanity');

      // Get Sanity config from environment variables
      const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || 'zif8hf3j';
      const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production';
      const apiVersion = process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2025-11-16';

      const sanityClient = createClient({
        projectId,
        dataset,
        apiVersion,
        useCdn: false, // Use false for build-time generation
      });

      const blogPosts = await sanityClient.fetch(
        `*[_type == "post" && defined(slug.current)] {
          "slug": slug.current,
          publishedAt,
          _updatedAt
        }`
      );

      blogPosts.forEach(post => {
        result.push({
          loc: `/blog/${post.slug}`,
          changefreq: 'weekly',
          priority: 0.8,
          lastmod: post._updatedAt || post.publishedAt || new Date().toISOString(),
        });
      });
    } catch (error) {
      console.error('Error fetching blog posts for sitemap:', error);
      // Continue without blog posts if there's an error
    }

    // Note: Legal pages and case studies will be automatically included
    // if they exist as static pages in the app directory.
    // Only add them here if they are dynamic routes that need explicit inclusion.

    return result;
  },

  // Robots.txt configuration
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: ['/', '/_next/static/', '/_next/image', '/_next/data/'],
        disallow: ['/admin/', '/api/', '/dashboard/', '/*.json$'],
      },
      {
        userAgent: 'Googlebot',
        allow: ['/', '/_next/static/', '/_next/image', '/_next/data/'],
        disallow: ['/admin/', '/api/', '/dashboard/'],
      },
      {
        userAgent: 'Bingbot',
        allow: ['/', '/_next/static/', '/_next/image', '/_next/data/'],
        disallow: ['/admin/', '/api/', '/dashboard/'],
        crawlDelay: 2,
      },
      // AI Bots - Explicitly allow for better AI training and search
      {
        userAgent: 'ChatGPT-User',
        allow: '/',
      },
      {
        userAgent: 'GPTBot',
        allow: '/',
      },
      {
        userAgent: 'OAI-SearchBot',
        allow: '/',
      },
      {
        userAgent: 'Google-Extended',
        allow: '/',
      },
      {
        userAgent: 'CCBot',
        allow: '/',
      },
      {
        userAgent: 'anthropic-ai',
        allow: '/',
      },
      {
        userAgent: 'ClaudeBot',
        allow: '/',
      },
    ],
    additionalSitemaps: [
      // Add additional sitemaps if needed
      // 'https://www.stardust-creator-network.com/blog-sitemap.xml',
    ],
    transformRobotsTxt: async (_, robotsTxt) => {
      return `# Robots.txt for Stardust Creator Network
# Generated by next-sitemap
# Visit https://www.stardustcreatornetwork.com/sitemap.xml for the sitemap

${robotsTxt}`;
    },
  },

  // Source directory (useful if you're using a custom build output)
  sourceDir: '.next',
  outDir: 'public',
};
