/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.SITE_URL || 'https://www.stardust-creator-network.com',
  generateRobotsTxt: true, // Generate robots.txt file
  sitemapSize: 7000, // Split sitemap if it exceeds this number of URLs
  changefreq: 'weekly',
  priority: 0.7,

  // Exclude certain paths from sitemap
  exclude: [
    '/admin/*',
    '/api/*',
    '/dashboard/*',
    '/404',
    '/500',
    '/_*',
    '/og/*', // Exclude OG image generation routes
  ],

  // Transform function to customize URLs in sitemap
  transform: async (config, path) => {
    // Custom priority based on path
    let priority = 0.7;
    let changefreq = 'weekly';

    if (path === '/') {
      priority = 1.0;
      changefreq = 'daily';
    } else if (path.startsWith('/blog/')) {
      priority = 0.8;
      changefreq = 'weekly';
    } else if (path.startsWith('/(marketing)/')) {
      priority = 0.6;
      changefreq = 'monthly';
    }

    return {
      loc: path,
      changefreq,
      priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
    };
  },

  // Additional paths to include (useful for dynamic routes)
  additionalPaths: async () => {
    const result = [];

    // Add blog posts dynamically (example)
    // const blogPosts = await fetchBlogPosts();
    // blogPosts.forEach((post) => {
    //   result.push({
    //     loc: `/blog/${post.slug}`,
    //     changefreq: 'weekly',
    //     priority: 0.8,
    //     lastmod: new Date(post.updatedAt).toISOString(),
    //   });
    // });

    return result;
  },

  // Robots.txt configuration
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/admin/', '/api/', '/dashboard/', '/_next/', '/*.json$', '/_*'],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: ['/admin/', '/api/', '/dashboard/'],
      },
    ],
    additionalSitemaps: [
      // Add additional sitemaps if needed
      // 'https://www.stardust-creator-network.com/blog-sitemap.xml',
    ],
    transformRobotsTxt: async (_, robotsTxt) => {
      return `# Robots.txt for Stardust Creator Network
# Generated by next-sitemap
# Visit https://www.stardust-creator-network.com/sitemap.xml for the sitemap

${robotsTxt}

# Custom rules
User-agent: Googlebot
Crawl-delay: 1

User-agent: Bingbot
Crawl-delay: 2

# Allow well-known paths
Allow: /.well-known/

# Block sensitive paths
Disallow: /search?
Disallow: /*?utm_*
Disallow: /*?ref=*

# Sitemap location
Sitemap: ${process.env.SITE_URL || 'https://www.stardust-creator-network.com'}/sitemap.xml`;
    },
  },

  // Source directory (useful if you're using a custom build output)
  sourceDir: '.next',
  outDir: 'public',
};
